version: '3'

services:
  msaggrworker:
    container_name: poc-entregas-msaggr
    build: 
      context: .
      dockerfile: DevDockerfile
    volumes:
      - ".:/app"
    networks:
      - pocNetwork
    depends_on:
      - msaggrdb
      - rabbit

#### use this service only when running this microservice solo on dev environment ##### 
  rabbit:
    image: rabbitmq:3-management
    container_name: msaggr-rabbit
    networks:
      - pocNetwork
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    ports:
    - 15672:15672
 
  msaggrdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: msdb
    networks:
      - pocNetwork

networks:
  pocNetwork:
    name: poc-network
    driver: bridge